#
#  mcMMO configuration
#    First generated on ${project.version}-b${BUILD_NUMBER}
#
#####

#
#  Settings for mcMMO in general
###
General:
    Locale: en_us
    MySpawn:
        Enabled: true
    MOTD:
        Enabled: true
    #Amount of time (in minutes) to wait between saves of player information
    Save_Interval: 10
    #Allow mcMMO to report on basic anonymous usage
    Stats_Tracking: true
    #Allow mcMMO to inform other plugins of damage being dealt
    Event_Callback: true

#
#  Settings for using a mySQL database
###
MySQL:
    Enabled: false
    Database:
        User:
            Name: UserName
            Password: UserPassword
        Name: DataBaseName
        TablePrefix: mcmmo_
    Server:
        Port: 3306
        Address: localhost

#
#  Settings for mcMMO items
###
Items:
    Chimaera_Wing:
        Enabled: true
        Feather_Cost: 10
        Item_ID: 288

#
#  Settings for Arcane Forging
###
Arcane_Forging:
    Keep_Enchants:
        Chance:
            Rank_4: 40
            Rank_3: 30
            Rank_2: 20
            Rank_1: 10
    May_Lose_Enchants:
        Enabled: true
    Downgrades:
        Enabled: true
        Chance:
            Rank_4: 15
            Rank_3: 25
            Rank_2: 50
            Rank_1: 75

#
#  Settings for Abilities
###
Abilities:
    Enabled: true
    Messages: true
    Activation:
        Only_Activate_When_Sneaking: false
    Cooldowns:
        Giga_Drill_Breaker: 240
        Berserk: 240
        Green_Terra: 240
        Skull_Splitter: 240
        Serrated_Strikes: 240
        Tree_Feller: 240
        Super_Breaker: 240
    Tools:
        Durability_Loss_Enabled: true
        Durability_Loss: 2

#
#  Settings for Skills
###
Skills:
    Acrobatics:
        Level_Cap: 0    #Level cap of 0 for no limit
    Archery:
        Level_Cap: 0
    Axes:
        Level_Cap: 0
    Excavation:
        Level_Cap: 0
        Requires_Shovel: true
    Fishing:
        Level_Cap: 0
    Herbalism:
        Level_Cap: 0
        Green_Thumb:
            Cobble_To_Mossy: true
            SmoothBrick_To_MossyBrick: true
            Dirt_To_Grass: true
        Hunger_Bonus: true
    Mining:
        Level_Cap: 0
        Requires_Pickaxe: true
    Repair:
        Level_Cap: 0
        Anvil_Messages: true
        Anvil_ID: 42
        Leather:
            Name: Leather
            ID: 334
        String:
            Name: String
            ID: 287
        Stone:
            Name: Cobblestone
            ID: 4
        Wood:
            Name: Wood Planks
            ID: 5
        Gold:
            Name: Gold Bars
            ID: 266
        Iron:
            Name: Iron Bars
            ID: 265
        Diamond:
            Name: Diamond
            Level_Required: 50
            ID: 264
    Swords:
        Level_Cap: 0
    Taming:
        Level_Cap: 0
        Call_Of_The_Wild:
            Bones_Required: 10
    Unarmed:
        Level_Cap: 0
    Woodcutting:
        Level_Cap: 0
        Requires_Axe: true

#
#  Settings for XP distribution
###
Experience:
    Gains:
        Mobspawners:
            Enabled: false
        Multiplier:
            PVP: 1
            Global: 1.0
    PVP:
        Rewards: true
    Formula:
        Multiplier:
            Swords: 1.0
            Taming: 1.0
            Acrobatics: 1.0
            Sorcery: 1.0
            Excavation: 1.0
            Herbalism: 1.0
            Unarmed: 1.0
            Woodcutting: 1.0
            Mining: 1.0
            Archery: 1.0
            Axes: 1.0
            Repair: 1.0
    Fishing:
        Base: 800
    Excavation:
        Base: 40
    Woodcutting:
        Birch: 70
        Spruce: 80
        Pine: 90
    Herbalism:
        Sugar_Cane: 30
        Cactus: 30
        Flowers: 100
        Pumpkin: 20
        Mushrooms: 150
        Wheat: 50
        Melon: 20
        Nether_Wart: 50
        Lily_Pads: 100
        Vines: 10
    Mining:
        Sandstone: 30
        Glowstone: 30
        Lapis: 400
        Obsidian: 150
        Stone: 30
        Netherrack: 30
        Gold: 350
        Redstone: 150
        Coal: 100
        Diamond: 750
        Iron: 250
        End_Stone: 150
        Moss_Stone: 30
    Taming:
        Shearing: 250
        Animal_Taming:
            Wolf: 250

#
#  Settings for Fishing
###
Fishing:
    Drops:
        Item_Drops_Enabled: true
        Drop_Chance:
            Tier_1: 20
            Tier_2: 25
            Tier_3: 30
            Tier_4: 35
            Tier_5: 40
        Gold_Tools: true
        Diamond_Armor: true
        Stone_Tools: true
        Diamonds: true
        Iron_Armor: true
        Iron_Tools: true
        Diamond_Tools: true
        Records: true
        Blaze_Rod: true
        Leather_Armor: true
        Gold_Armor: true
        Glowstone_Dust: true
        Ender_Pearl: true
        Wooden_Tools: true

#
#  Settings for Excavation
###
Excavation:
    Treasure:
        - Cake
        - Gunpowder
        - Bone
        - Apple
        - Slimeball
        - Bucket
        - Netherrack
        - Red_Mushroom
        - Brown_Mushroom
        - Egg
        - Soul_Sand
        - Clock
        - Cobweb
        - String
        - Glowstone_Dust
        - Gold_Music
        - Green_Music
        - Diamond
        - Cocoa_Beans

#
#  Configuration to define Treasures
###
Treasures:
    Cake:
        ID: 354
        Data: 0
        Amount: 1
        XP: 3000
        Drop_Chance: 0.05
        Drop_Level: 750
        Drops_From:
            Dirt: true
            Grass: true
            Sand: true
            Gravel: true
            Clay: true
            Mycelium: true
            Soul_Sand: true
    Gunpowder:
        ID: 289
        Data: 0
        Amount: 1
        XP: 30
        Drop_Chance: 10.0
        Drop_Level: 75
        Drops_From:
            Gravel: true
    Bone:
        ID: 352
        Data: 0
        Amount: 1
        XP: 30
        Drop_Chance: 10.0
        Drop_Level: 175
        Drops_From:
            Gravel: true
    Apple:
        ID: 260
        Data: 0
        Amount: 1
        XP: 100
        Drop_Chance: 0.1
        Drop_Level: 250
        Drops_From:
            Grass: true
            Mycelium: true
    Slimeball:
        ID: 341
        Data: 0
        Amount: 1
        XP: 100
        Drop_Chance: 5.0
        Drop_Level: 150
        Drops_From:
            Clay: true
    Bucket:
        ID: 325
        Data: 0
        Amount: 1
        XP: 100
        Drop_Chance: 0.1
        Drop_Level: 500
        Drops_From:
            Clay: true
    Netherrack:
        ID: 87
        Data: 0
        Amount: 1
        XP: 30
        Drop_Chance: 0.5
        Drop_Level: 850
        Drops_From:
            Gravel: true
    Red_Mushroom:
        ID: 40
        Data: 0
        Amount: 1
        XP: 80
        Drop_Chance: 0.5
        Drop_Level: 500
        Drops_From:
            Dirt: true
            Grass: true
            Mycelium: true
    Brown_Mushroom:
        ID: 39
        Data: 0
        Amount: 1
        XP: 80
        Drop_Chance: 0.5
        Drop_Level: 500
        Drops_From:
            Dirt: true
            Grass: true
            Mycelium: true
    Egg:
        ID: 344
        Data: 0
        Amount: 1
        XP: 100
        Drop_Chance: 1.0
        Drop_Level: 250
        Drops_From:
            Grass: true
    Soul_Sand:
        ID: 88
        Data: 0
        Amount: 1
        XP: 80
        Drop_Chance: 0.5
        Drop_Level: 650
        Drops_From:
            Sand: true
    Clock:
        ID: 347
        Data: 0
        Amount: 1
        XP: 100
        Drop_Chance: 0.1
        Drop_Level: 500
        Drops_From:
            Clay: true
    Cobweb:
        ID: 30
        Data: 0
        Amount: 1
        XP: 150
        Drop_Chance: 5.0
        Drop_Level: 750
        Drops_From:
            Clay: true
    String:
        ID: 287
        Data: 0
        Amount: 1
        XP: 200
        Drop_Chance: 5.0
        Drop_Level: 250
        Drops_From:
            Clay: true
    Glowstone_Dust:
        ID: 348
        Data: 0
        Amount: 1
        XP: 80
        Drop_Chance: 5.0
        Drop_Level: 25
        Drops_From:
            Dirt: true
            Grass: true
            Sand: true
            Mycelium: true
    Gold_Music:
        ID: 2256
        Data: 0
        Amount: 1
        XP: 3000
        Drop_Chance: 0.05
        Drop_Level: 250
        Drops_From:
            Dirt: true
            Grass: true
            Sand: true
            Gravel: true
            Clay: true
            Mycelium: true
            Soul_Sand: true
    Green_Music:
        ID: 2257
        Data: 0
        Amount: 1
        XP: 3000
        Drop_Chance: 0.05
        Drop_Level: 250
        Drops_From:
            Dirt: true
            Grass: true
            Sand: true
            Gravel: true
            Clay: true
            Mycelium: true
            Soul_Sand: true
    Diamond:
        ID: 264
        Data: 0
        Amount: 1
        XP: 1000
        Drop_Chance: 0.13
        Drop_Level: 350
        Drops_From:
            Dirt: true
            Grass: true
            Sand: true
            Gravel: true
            Clay: true
            Mycelium: true
            Soul_Sand: true
    Cocoa_Beans:
        ID: 351
        Data: 3
        Amount: 1
        XP: 100
        Drop_Chance: 1.33
        Drop_Level: 350
        Drops_From:
            Dirt: true
            Grass: true
            Sand: true
            Gravel: true
            Clay: true
            Mycelium: true
            Soul_Sand: true

#
#  Settings for commands
###
Commands:
    invite:
        Enabled: true
    mctop:
        Enabled: true
    xplock:
        Enabled: true
    whois:
        Enabled: true
    mcc:
        Enabled: true
    mmoedit:
        Enabled: true
    accept:
        Enabled: true
    stats:
        Enabled: true
    mcability:
        Enabled: true
    party:
        Enabled: true
    xprate:
        Enabled: true
    mcgod:
        Enabled: true
    mcmmo:
        Enabled: true
        Donate_Message: true
    mcrefresh:
        Enabled: true
    myspawn:
        Enabled: true
    addxp:
        Enabled: true
    clearmyspawn:
        Enabled: true
    ptp:
        Enabled: true
    p:
        Enabled: true
        Display_Names: true
    a:
        Enabled: true
        Display_Names: true

#
#  Settings for Spout features
###
Spout:
    Menu:
        Key: KEY_M
    XP:
        Bar:
            Enabled: true
            X_POS: 95
            Y_POS: 6
        Icon:
            Enabled: true
            X_POS: 78
            Y_POS: 2
    Party:
        HUD:
            Show_Faces: true
            Enabled: true
            Show_Display_Name: false
    HUD:
        Default: STANDARD
        Retro:
            Colors:
                Swords:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Taming:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Acrobatics:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Border:
                    BLUE: 0.0
                    GREEN: 0.0
                    RED: 0.0
                Background:
                    BLUE: 0.75
                    GREEN: 0.75
                    RED: 0.75
                Woodcutting:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Archery:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Axes:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Repair:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Fishing:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Excavation:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Herbalism:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Unarmed:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Mining:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3